import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "./components/navigationBar";
import { AppWrapper } from "./context";
import ProgressBar from "./components/progressBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppWrapper>
        <ProgressBar/>
        {children}
        <NavigationBar/>
        </AppWrapper>
        </body>
    </html>
  );
}
